users:
  - id: 1
    id_murid: null
    name: DAVIN WAHYU WARDANA
    id_kelas: 1
    nis: '3344235'
    created_at: '2023-11-13T18:05:51.000000Z'
    updated_at: '2023-11-13T18:05:51.000000Z'

berita_sekolah:
  - id: 1
    judul: Contoh Berita Sekolah 1
    konten: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    created_at: '2023-12-17T08:00:00.000000Z'
    updated_at: '2023-12-17T08:00:00.000000Z'